### ISSUE TITLE
Couldn't find module 'gulp-bower'

### ISSUE THREAD

**Issue by boogerlad** [Karnith/sails-generate-bower-gulp#1]
```
verbose: Gulp :: [15:57:49] Starting 'default'...
verbose: Gulp :: [15:57:49] Starting 'compileAssets'...
verbose: Gulp :: [15:57:49] Starting 'bower:install'...
verbose: Gulp :: [15:57:49] 'bower:install' errored after 3.65 ms
verbose: Gulp :: [15:57:49] Error: Cannot find module 'gulp-bower'
    at Function.Module._resolveFilename (module.js:322:15)
    at Function.Module._load (module.js:264:25)
    at Module.require (module.js:351:17)
    at require (module.js:370:17)
    at Object.defineProperty.get (/usr/lib/node_modules/gulp-load-plugins/index.js:56:18)
    at Gulp.<anonymous> (/root/gulpbower2/tasks/config/bower.js:12:17)
    at module.exports (/usr/lib/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/usr/lib/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/usr/lib/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/usr/lib/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
verbose: Gulp :: [15:57:49] 'default' errored after 15 ms
verbose: Gulp :: [15:57:49] Error: [object Object]
    at formatError (/usr/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/lib/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.emit (events.js:117:20)
    at Gulp.Orchestrator._emitTaskDone (/usr/lib/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /usr/lib/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/usr/lib/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/usr/lib/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at finish (/usr/lib/node_modules/run-sequence/index.js:48:5)
    at Gulp.onError (/usr/lib/node_modules/run-sequence/index.js:55:4)
    at Gulp.emit (events.js:117:20)
verbose: Gulp :: [15:57:49] 'compileAssets' errored after 8.76 ms
verbose: Gulp :: [15:57:49] Error: [object Object]
    at formatError (/usr/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/lib/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.emit (events.js:117:20)
    at Gulp.Orchestrator._emitTaskDone (/usr/lib/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /usr/lib/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/usr/lib/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/usr/lib/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at finish (/usr/lib/node_modules/run-sequence/index.js:48:5)
    at Gulp.onError (/usr/lib/node_modules/run-sequence/index.js:55:4)
    at Gulp.emit (events.js:117:20)
verbose: Gulp :: [15:57:49] 'compileAssets' errored after 9.82 ms
verbose: Gulp :: [15:57:49] Error: [object Object]
    at formatError (/usr/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/lib/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.emit (events.js:117:20)
    at Gulp.Orchestrator._emitTaskDone (/usr/lib/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /usr/lib/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/usr/lib/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/usr/lib/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at finish (/usr/lib/node_modules/run-sequence/index.js:48:5)
    at Gulp.onError (/usr/lib/node_modules/run-sequence/index.js:55:4)
    at Gulp.emit (events.js:117:20)

```

I'm using sails 0.11-rc5

**Comment by boogerlad** [comment]
It appears I need `gulp-bower` and `main-bower-files` installed globally, not locally.

**Comment by Karnith** [comment]
Is gulp-bower in node_modules?

-------- Original message --------

**Comment by boogerlad** [comment]
yes. Is it by design your generators need their dependencies globally?

**Comment by Karnith** [comment]
all my generators need to be global, to create the project space. Bower is the only one that needs global in terms of packages.

**Comment by boogerlad** [comment]
Hmm that's odd. I suppose I can keep using it like this for now with all dependencies installed as global. As an aside, what exactly does `bower:install` task do? What benefit does it have over bower install? It seems redundant if the files are already there.
